name: "Prod Deploy"

permissions:
  actions: read
  contents: read
  id-token: write

on:
  push:
    tags:
      - "v**"
  workflow_dispatch:

jobs:
  test_and_build:
    name: "Build, Test and Archive"
    runs-on: [self-hosted, kubernetes, on-prem]
    container:
      image: "${{ vars.GH_WORKFLOW_DOCKER_IMAGE }}:${{ vars.GH_WORKFLOW_DOCKER_IMAGE_VERSION }}"
      credentials:
        username: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_PASSWORD }}
    strategy:
      fail-fast: false
      matrix:
        artifact:
          [
            arrival-events-relay,
            arrivals-event-processor,
            arrivals-desp-consumer,
            arrivals-core-workloads,
            arrivals-rest-api,
            database-utilities,
          ]
        include:
          - artifact: arrival-events-relay
            working-directory: src/arrival-events-relay
          - artifact: arrivals-event-processor
            working-directory: src/arrivals-event-processor
          - artifact: arrivals-desp-consumer
            working-directory: src/arrivals-core-desp-consumer-func
          - artifact: arrivals-core-workloads
            working-directory: src/arrivals-core-workloads
          - artifact: arrivals-rest-api
            working-directory: src/arrivals-rest-api
          - artifact: database-utilities
            build-directory: src/database-utilities/dist/sproc-out
            working-directory: src/database-utilities
    steps:
      - uses: actions/checkout@v3
      # TODO: track bug https://github.com/actions/checkout/issues/1169 which requires the next step
      - run: git config --system --add safe.directory $(pwd)
      - name: "Build and Test"
        uses: ./.github/actions/build-and-test
        with:
          npm-auth: ${{ secrets.NPM_AUTH }}
          working-directory: ${{ matrix.working-directory }}
      - name: "Archive"
        uses: ./.github/actions/archive
        with:
          artifact-name: ${{ matrix.artifact }}
          retention-days: 7
          working-directory: ${{ matrix.build-directory || matrix.working-directory }}

  deploy-test:
    name: "Deploy Pre-prod"
    needs: [test_and_build]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: test
    secrets: inherit

  deploy-prod:
    name: "Deploy Prod"
    needs: [deploy-test]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: prod
    secrets: inherit
