name: Version NPM package

on:
  workflow_dispatch:

jobs:
  version-and-publish:
    name: "Release if we have a version label"

    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global --replace-all user.name "$GITHUB_ACTOR"
          git config --global --replace-all user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git fetch --tags -f

      - name: Version root package
        if: ${{ steps.version-label.outputs.level != null }}
        run: npm run version:root ${{ steps.version-label.outputs.level }}

      - name: Bump NPM version and push
        id: bumpandpush
        if: ${{ steps.version-label.outputs.level != null }}
        run: |
          npm run publish:all ${{ steps.version-label.outputs.level }}
